random_forest_params:
  enabled: true
  n_estimators: 500
  max_depth: 20
  min_samples_leaf: 20
  n_jobs: -1
  random_state: 42
xgboost_params:
  enabled: true
  n_estimators: 1500
  learning_rate: 0.01
  max_depth: 6
  subsample: 0.8
  colsample_bytree: 0.8
  objective: reg:squarederror
  tree_method: hist
  random_state: 42
lightgbm_params:
  enabled: true
  objective: regression
  n_estimators: 2000
  learning_rate: 0.01
  num_leaves: 64
  min_data_in_leaf: 50
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
best_model/name: lightgbm
